In [1]:
import numpy as np
x=np.array([1,2,3])
print(x)

[1 2 3]


In [8]:
import torch
a=torch.tensor([1,2,3,4],dtype=torch.float)
b=torch.from_numpy(x)
print(a,b)
q=a.numpy()
print(q)

tensor([1., 2., 3., 4.]) tensor([1, 2, 3], dtype=torch.int32)
[1. 2. 3. 4.]


In [12]:
l=[[1,2],[3,4]]
temp1,temp2=zip(*l)
print(temp1,temp2)

(1, 3) (2, 4)


In [15]:
import gym
env_name='CartPole-v0'
env=gym.make(env_name)
print(env.action_space.n,env.observation_space.shape[0])

2 4


In [19]:
a,b={4:2,3:5}
print(a,b)

4 3


In [27]:
temp=torch.tensor(1)
print(temp,temp.shape,temp.item())
temp=torch.tensor([1])
print(temp,temp.shape,temp.item())

tensor(1) torch.Size([]) 1
tensor([1]) torch.Size([1]) 1


In [29]:
temp=np.array(1)
print(temp,temp.shape,temp.item())
temp=np.array([1,1])
print(temp,temp.shape,temp.item())

1 () 1


ValueError: can only convert an array of size 1 to a Python scalar