In [10]:
import torch
import matplotlib.pyplot as plt
from matplotlib import pyplot as plt
import numpy as np

In [5]:
import bisect
a=[1,2,3]
bisect.bisect_left(a,1.5,lo=0,hi=1)

1

In [2]:
import torch
import torch.nn as nn
x_input=torch.randn(3,3)#随机生成输入
print('x_input:\n',x_input)
y_target=torch.tensor([1,2,0])#设置输出具体值 print('y_target\n',y_target)

x_input:
 tensor([[ 0.6920,  1.0831, -0.6350],
        [ 1.8881, -0.5087,  0.2327],
        [ 0.2145, -1.5189, -1.1877]])


In [4]:
ll=x_input.long()
print(ll,ll.type(),type(ll))

tensor([[ 0,  1,  0],
        [ 1,  0,  0],
        [ 0, -1, -1]]) torch.LongTensor <class 'torch.Tensor'>


In [5]:
print(y_target,y_target.type(),x_input.type())

tensor([1, 2, 0]) torch.LongTensor torch.FloatTensor


In [6]:
crossentropyloss=nn.CrossEntropyLoss()
crossentropyloss_output=crossentropyloss(x_input,y_target)
print('crossentropyloss_output:\n',crossentropyloss_output)

crossentropyloss_output:
 tensor(0.5111)


In [9]:
device=torch.device('cuda')
a=torch.tensor([1,2,3],device=device)
print(a)
b=a.cpu().numpy()
print(b)

tensor([1, 2, 3], device='cuda:0')
[1 2 3]


In [3]:
import numpy as np
a=np.ones(shape=(2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [4]:
a=np.zeros_like(a)
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [5]:
b=np.eye(5)
print(b)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [7]:
a=np.diag([[1,2,3],[4,5,6]])
print(a)

[1 5]


In [10]:
a=np.array([[1,2,3],[4,5,6]])
print(a[:,:2])

[[1 2]
 [4 5]]
[[1 2 3]
 [4 5 6]]


In [11]:
import torch

In [14]:
a=torch.ones(size=(3,4))
print(a,a.type())

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) torch.FloatTensor


In [16]:
b=a.double()
print(b,b.type())

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64) torch.DoubleTensor


In [19]:
s=np.random.normal(0,1,10000)
print(s)

[ 1.23627061  1.31666031 -0.92975417 ... -1.80030162  0.52058881
  2.29521087]


In [22]:
print(np.mean(s),np.std([1,2,3]))

0.005283720802146667 0.816496580927726


In [29]:
a=[1,2,4]
b=[4,5,6]
print(list(zip(a,b)))#压缩
temp=zip(a,b)
c,d=zip(*temp)#解压缩
print(c,d)

[(1, 4), (2, 5), (4, 6)]
(1, 2, 4) (4, 5, 6)


In [30]:
a=[1,2,3]
x,y,z=a
print(x,y,z)

1 2 3


In [ ]:
np.random.sample()

In [8]:
import random
a=[1,2,2,3]
print(random.sample(a,3))

[1, 3, 2]


In [16]:
a=np.array([1,2,3])
print(np.random.choice(a,size=(5,5),replace=True))

[[2 1 3 1 3]
 [1 2 1 2 1]
 [3 2 3 1 2]
 [2 2 3 2 3]
 [2 3 1 2 3]]


In [17]:
print(np.minimum((1,2,3),(3,2,1)))

[1 2 1]


In [21]:
print(torch.mean(torch.tensor([3,4,5],dtype=torch.float)),np.mean([1,2,3]))

tensor(4.) 2.0
